# Generated by Django 5.0.6 on 2024-06-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='data_publicaco',
            new_name='data_publicacao',
        ),
    ]
